Use named Vue component classes
Qiskit/qiskit.org pull request #1130
Opened 2020-11-18 21:51 UTC by techtolentino

Fixes #1103 

Added named components that now show up in Vue dev-tools:

![Screen Shot 2020-11-18 at 2 50 30 PM](https://user-images.githubusercontent.com/6276074/99592461-7c836900-29ad-11eb-8a27-0e397727195b.png)

2020-11-19 08:58 UTC, y4izus requested changes
Great job Randy! just two small changes :)

2020-11-19 08:58 UTC, y4izus commented on components/learn/TheLearnHeader.vue
> +export default class ThLearnHeader extends Vue { }
Typo: ThLearnHeader => Th**e**LearnHeader

2020-11-19 08:58 UTC, y4izus commented on pages/events/_slug.vue
> +export default class EventsPage extends QiskitPage {
I think `EventPage` or `EventEntry` is more appropriate because this component is for a single event's page

2020-11-19 11:07 UTC, korgan00 commented
I want to suggest something.
The pages could be named as XxxxxPage. On one hand, we have the LandingPage and on the other hand Advocates and Events.
If you ask me what "Advocates" class should do, I think about multiple responsibilities such as a special collection class, a component showing several advocates... But I think AdvocatesPage is clear.
As [Yaiza said](https://github.com/Qiskit/qiskit.org/pull/1130#discussion_r526692115), the _slug pages I like the XxxxEntry option.

2020-11-19 15:52 UTC, eddybrando approved these changes
Nice work! 🙂

2020-11-19 16:54 UTC, korgan00 approved these changes

2020-11-20 10:50 UTC, korgan00 approved these changes
Good job!

2020-11-23 14:09 UTC, y4izus approved these changes

2020-11-23 15:20 UTC, merged