Fix/gi i973 unified and refactor ctas
Qiskit/qiskit.org pull request #1145
Opened 2020-11-24 17:01 UTC by korgan00

Fix #973

2020-11-25 15:08 UTC, y4izus requested changes
Thank you, Goyo! I know this is a hard refactor and maybe the review will be also. May the force be with you! 💪  If you need help, just let me know!. 

Let's start the review with the styles:

- When hovering on the primary cta on the home page, the text turns into blue
<img width="383" alt="Screen Shot 2020-11-25 at 15 49 13" src="https://user-images.githubusercontent.com/17231966/100243060-c633fc80-2f35-11eb-9e8c-8c9d4a6c756d.png">

- Links on the Quick start section doesn't follow the same styles (I didn't visit the link and its already purple)
<img width="418" alt="Screen Shot 2020-11-25 at 15 50 53" src="https://user-images.githubusercontent.com/17231966/100243299-01cec680-2f36-11eb-9020-7aca976d763c.png">

- Same here:
<img width="291" alt="Screen Shot 2020-11-25 at 15 55 43" src="https://user-images.githubusercontent.com/17231966/100243921-af41da00-2f36-11eb-96ef-0a7edac85ab3.png">

- There is a moment when hovering the IBM Quantum Experience that the link turns blue but I wasn't able to take the picture. 

- Same for the "Get started" and "See docs" on `/overview`
<img width="250" alt="Screen Shot 2020-11-25 at 15 58 13" src="https://user-images.githubusercontent.com/17231966/100244287-09429f80-2f37-11eb-9694-691f5f4f36ad.png">


- The ghost cta color should be purple and here it's blue
<img width="555" alt="Screen Shot 2020-11-25 at 15 54 19" src="https://user-images.githubusercontent.com/17231966/100243732-7bff4b00-2f36-11eb-8a36-e54fce56847f.png">

- Ghost links on learn page, are blue instead of purple
<img width="957" alt="Screen Shot 2020-11-25 at 16 00 13" src="https://user-images.githubusercontent.com/17231966/100244519-4eff6800-2f37-11eb-91a6-8374a67bf1cf.png">

- Text has disappear from the primary cta to start an event. When  hovering turns into blue and then into purple
<img width="459" alt="Screen Shot 2020-11-25 at 16 04 44" src="https://user-images.githubusercontent.com/17231966/100245072-f086b980-2f37-11eb-8415-09d7411dbd30.png">

When you finish, please, ask me for a second review

2020-11-26 10:14 UTC, y4izus requested changes
Thanks for implementing the first requested chages! Let's go with the second round:

- Please, review all the primary and secondary ctas on small devices, they are all too big:
<img width="429" alt="Screen Shot 2020-11-26 at 11 10 46" src="https://user-images.githubusercontent.com/17231966/100337714-09df4280-2fd8-11eb-8b85-9ff14e1aa0ff.png">
<img width="410" alt="Screen Shot 2020-11-26 at 11 11 09" src="https://user-images.githubusercontent.com/17231966/100337767-182d5e80-2fd8-11eb-87f1-4f2ba626f46a.png">
<img width="422" alt="Screen Shot 2020-11-26 at 11 11 21" src="https://user-images.githubusercontent.com/17231966/100337794-1ebbd600-2fd8-11eb-9463-1f6d0c2b2668.png">
and so on...

- I also added some comments on the code 👇 

Ask me for another review when you finished! 💪 💪

2020-11-26 10:14 UTC, y4izus commented on components/ui/AppCta.vue
> +    if (AppLink.isExternal(this.$attrs.url)) {
You're using `this.$attrs.url` two times, could you extract it to a variable?

2020-11-26 10:14 UTC, y4izus commented on pages/events/index.vue
> -    &__cta {
You forgot to remove the [line where this class was used](https://github.com/Qiskit/qiskit.org/pull/1145/files#diff-e89e9da7098c8b828fffda21f9b905c5668d8726f92332ddd3612c55d7bc0d9eR77)

2020-11-30 18:49 UTC, techtolentino approved these changes
@korgan00 - great work! I only had two small updates to the labels... 

thank you

2020-11-30 18:49 UTC, techtolentino commented on components/landing/TheFeatures/index.vue
> +    label: 'Full Overview',
@korgan00 - please up date this label to `Full overview`

2020-11-30 18:49 UTC, techtolentino commented on components/landing/TheLearnSection/LearnCard.vue
> +    label: 'Get Learning',
same type of comment here, please update the label to `Get learning`

2020-12-02 14:01 UTC, eddybrando approved these changes
Awesome job, @korgan00! Thanks a lot!

I really like the great effort put into unifying our buttons and links.

I have just some small suggestions regarding styling _:focus_ similarly to _:hover_ and probably adding a couple of lines more of documentation for future reference. 🙂

2020-12-02 14:57 UTC, eddybrando approved these changes
Awesome, thanks a lot for the changes @korgan00 🙂

2020-12-03 10:35 UTC, y4izus approved these changes
You did an awesome job @korgan00 !!! thank you very much!!

2020-12-03 10:35 UTC, y4izus commented on components/layouts/banners/TheBlackLivesMatterBanner.vue
> +  // Rely on BEM specifity because of the problems of css inconsistent ordering on nuxt compilation.
Thank you for this reference!

2020-12-03 10:36 UTC, merged

2020-12-03 15:27 UTC, JRussellHuffman commented
Looked over everything. Overall, its great! Noticed a handful of things.
- the background gray on the secondary button should be cool-gray-10 (#F2F4F8). Right now its #f4f4f4
- not sure if the quick start options are a part of this scope, but the text should be cool gray 80
- the downward arrow on the “Get Started” CTA on the overview page looks shifted down by a few pixels by default. It might not be, but wanted to flag it just in case

2020-12-03 15:56 UTC, JRussellHuffman commented
created a separate issue for the quick start text color #1206

2020-12-08 09:16 UTC, y4izus commented
Fixes #1204