Update site mobile menu [wip]
Qiskit/qiskit.org pull request #1221
Opened 2020-12-07 22:03 UTC by techtolentino

2020-12-09 21:53 UTC, techtolentino commented
@JRussellHuffman - tagging you here to let you know of an issue I ran into (please see notes above, 2nd bullet point).

You can also view the mobile nav updates [here](https://qiskitorg-git-rt-1183-mobile-nav-updates.qiskit.now.sh/)

2020-12-10 10:56 UTC, y4izus requested changes
Thanks Randy!

Could you check with Russell if the menu is ok for mobile devices? On Figme he has this design:

<img width="505" alt="Screen Shot 2020-12-10 at 11 55 42" src="https://user-images.githubusercontent.com/17231966/101763112-a3314d00-3ade-11eb-8515-049213baeaa7.png">

And we have the same menu that we have for medium size:

<img width="350" alt="Screen Shot 2020-12-10 at 11 56 06" src="https://user-images.githubusercontent.com/17231966/101763159-b217ff80-3ade-11eb-9d38-7e896ff70a55.png">

2021-01-19 17:21 UTC, delapuente requested changes
Nice work, @techtolentino. You did it! Please, address my comments below.

2021-01-19 17:21 UTC, delapuente commented on components/layouts/TheMenu/MobileMenu.vue
> +  /**
Avoid explaining what the function does in a comment, change the name of the function to something like `openDropdown` and you will remove the need for further explanations and, by the way, prevent the name collision with the const `showDropMenu`.

2021-01-19 17:21 UTC, delapuente commented on components/layouts/TheMenu/MobileMenu.vue
> +  isMobileMenuVisible: boolean=false
The component is the `MobileMenu` already so you can remove context from the name and simply call it `isVisible`.

2021-01-19 17:21 UTC, delapuente commented on components/layouts/TheMenu/MobileMenu.vue
> +  @Prop({ type: Boolean, default: false })
Usually, we write the property name following the decorator. Take a look at other components to see how.

2021-01-19 17:21 UTC, delapuente commented on components/layouts/TheMenu/index.vue
> +  isCommunityDropdownVisible = false
I did not find any use of this field in the code. Is it safe to remove completely?

2021-01-23 00:22 UTC, delapuente approved these changes
Nice done @techtolentino. Happy to see the mobile menu in place!

2021-01-23 00:23 UTC, delapuente commented
@y4izus would you mind double-checking the visual implementation?

2021-01-25 09:00 UTC, y4izus commented
@techtolentino , could you double-check with Russell this styles:

- On medium size: Check if the bottom content is correct
  - Figma design
  
<img width="164" alt="Screen Shot 2021-01-25 at 09 56 43" src="https://user-images.githubusercontent.com/17231966/105683177-a4ce9d00-5ef3-11eb-8b32-3c47b6d3f492.png">

  - PR design
<img width="195" alt="Screen Shot 2021-01-25 at 09 57 10" src="https://user-images.githubusercontent.com/17231966/105683222-b3b54f80-5ef3-11eb-9647-f136ff0a16d9.png">

- On small size: Check if the footer should be sticky to the bottom
  - Figma design
  
<img width="290" alt="Screen Shot 2021-01-25 at 09 58 32" src="https://user-images.githubusercontent.com/17231966/105683402-e4958480-5ef3-11eb-999b-1163ff321c44.png">

  - PR design
  
<img width="349" alt="Screen Shot 2021-01-25 at 09 59 23" src="https://user-images.githubusercontent.com/17231966/105683529-0262e980-5ef4-11eb-9d85-5823ed579290.png">

2021-02-02 11:29 UTC, y4izus approved these changes
Thank you Randy!

2021-02-02 11:29 UTC, merged