Technical architecture overview
Qiskit/qiskit.org pull request #1225
Opened 2020-12-08 14:14 UTC by eddybrando

Expanded technical architecture overview section in the **README.md** file as suggested in #1030.

---

Closes #1030

2021-01-11 21:19 UTC, techtolentino approved these changes
Such a good addition to the project documentation. Thank you @eddybrando for the thoroughness.

2021-01-19 16:59 UTC, delapuente requested changes
The general comment is that the content is too shallow. We should make it deeper and try to add more value to the developer.

Also, it would be convenient to tell how some parts connect with others.

2021-03-09 21:55 UTC, delapuente commented
How is this goind @eddybrando ? Do you have any blocker?

2021-04-06 12:36 UTC, eddybrando commented on ARCHITECTURE.md
> +Here is an example of a component called `GreetingMessage.vue`:
Followed up on https://github.com/Qiskit/qiskit.org/pull/1654#discussion_r607798635 and addressed on #1654

2021-04-06 12:57 UTC, eddybrando commented on ARCHITECTURE.md
> +### content (old)
Followed up on https://github.com/Qiskit/qiskit.org/pull/1654/files#r607821692 and addressed with #1654

2021-04-27 12:23 UTC, delapuente commented
Superseded by #1654

2021-04-27 12:23 UTC, closed without merging