Create seminar series data table component
Qiskit/qiskit.org pull request #1305
Opened 2021-01-13 12:02 UTC by y4izus

Fix #1298

2021-01-14 17:18 UTC, techtolentino requested changes
@y4izus - nice work with implementing the table!

One comment regarding cell widths, on mobile.

In the design for mobile, the cell widths give a little more room for the cell data to display... 

![Screen Shot 2021-01-14 at 10 07 19 AM](https://user-images.githubusercontent.com/6276074/104624823-467f0000-5651-11eb-8c22-5bd07edc78f6.png)


In this PR, the _mobile_ table looks like so:
![Screen Shot 2021-01-14 at 10 10 42 AM](https://user-images.githubusercontent.com/6276074/104624976-74644480-5651-11eb-94f8-def5904b0dd4.png)



In the design, it looks like cell widths are based on column widths... if we can use that, that would be awesome. If not, I think we'd still provide great UX if we could designate a width or even a min-width, so that the cell data is more readable.


I also realize that this could happen in a follow-up PR as well (if we all agree)

Thoughts?

2021-01-14 17:43 UTC, techtolentino commented
Last question - are you seeing these warnings in the console? Or is this just my local...

![Uploading Screen Shot 2021-01-14 at 10.43.04 AM.png…]()

2021-01-15 08:18 UTC, y4izus commented on components/events/single-events/SeminarSeriesDataTable.vue
> +  columns = ['Speaker', 'Name of talk', 'Institution', 'Date of talk', 'Link to talk']
Sure!

2021-01-15 08:21 UTC, y4izus commented
I can see your image with the warnings on the console, but I will take a look ;).

Related to the columns' width, I just use the carbon design component and didn't look at that (honestly). I'll try to improve it

2021-01-15 11:11 UTC, eddybrando approved these changes
Awesome @y4izus thanks a lot!

2021-01-15 11:14 UTC, merged