Better definition for next event
Qiskit/qiskit.org pull request #1392
Opened 2021-02-03 16:16 UTC by y4izus

2021-02-03 19:56 UTC, techtolentino commented on pages/events/seminar-series.vue
> +  nextEvent = this.hasUpcomingEvents ? upcomingSeminarSerieEvents[0] : null
@y4izus - this change looks good to me... 

the PR just needs to be updated to resolve conflicts

2021-02-04 09:21 UTC, korgan00 requested changes

2021-02-04 09:21 UTC, korgan00 commented on pages/events/seminar-series.vue
> +  nextEvent = this.hasUpcomingEvents ? upcomingSeminarSerieEvents[0] : null
Good job, @y4izus 

Just one thing. I think that is good to unify the use of `upcomingEvents` instead of using `upcomingSeminarSerieEvents`.

2021-02-04 12:10 UTC, korgan00 approved these changes

2021-02-04 12:21 UTC, merged