feat: add technical architecture overview
Qiskit/qiskit.org pull request #1654
Opened 2021-04-06 12:14 UTC by eddybrando

2021-04-06 12:21 UTC, eddybrando commented on ARCHITECTURE.md
> +Here is an example of a component called `GreetingMessage.vue`:
From https://github.com/Qiskit/qiskit.org/pull/1225#discussion_r560228814 by @delapuente:

> Would be convenient to provide an example based on a real one.

My goal with this code snippet is to give a very quick glance at the use of TypeScript and SCSS in our Vue components. I believe that using a real example may add more elements and divert to attention to other more complex parts of a component.

Nevertheless I see value in displaying a code snipped with an example of a simplified version of a real project component.

2021-04-06 12:53 UTC, eddybrando commented on ARCHITECTURE.md
> +### content (old)
From https://github.com/Qiskit/qiskit.org/pull/1225/files#r560230565 by @delapuente:

> Would be convenient to mention the front-matter & markdown plugin we are using.

2021-07-13 00:30 UTC, delapuente approved these changes
Let's unblock this. There will be more opportunities to improve it!

2021-07-13 00:31 UTC, delapuente commented
@y4izus please take a look, add your comments and let's merge this.

@eddybrando nice done, please update whatever you consider it should be updated and prepare the branch for merging.

2021-07-13 10:21 UTC, y4izus requested changes
Great job Eddy! just one comment and we can merge :D

2021-07-13 10:21 UTC, y4izus commented on README.md
>  We create and run unit tests using [Jest](https://jestjs.io/), ensure avoiding syntax errors using [ESLint](https://eslint.org/) and automate all these previous tools and deployment using [Travis](ht
Right now we are using Github actions instead of travis

2021-07-14 16:44 UTC, delapuente approved these changes

2021-07-14 16:44 UTC, merged