Summer school content changes
Qiskit/qiskit.org pull request #1717
Opened 2021-04-20 16:48 UTC by korgan00

2021-04-20 16:55 UTC, techtolentino approved these changes
looks good, @korgan00

2021-04-21 09:47 UTC, y4izus requested changes
Please, review my suggestions and ask me for another review. I will like to review again the action messages once these changes will be done

2021-04-21 09:47 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
> +  segment: mailto-quantum-educators
We are trying to unify how we do things, so, until we find a better way to do it, please, follow here the same structure as we have on `summer-school-2021.yaml`:

```
segment:
      action: 'events-summer-school > faq > mailto-quantum-educators'
```

Same for all the links. And please, remove the code you don't need

2021-04-21 09:47 UTC, y4izus commented on new-content/events/summer-school-2021.yaml
> +      action: 'events-summer-school > header > learn-more'
```suggestion
      action: 'events-summer-school > header > qiskit-org-home'
```

2021-04-21 09:47 UTC, y4izus commented on new-content/events/summer-school-2021.yaml
> +      action: 'events-summer-school > header > learn-more'
```suggestion
      action: 'events-summer-school > header > qiskit-org-home'
```

2021-04-21 09:47 UTC, y4izus commented on new-content/events/summer-school-2021.yaml
>      url: 'https://qiskit.org'
Ask @JRussellHuffman if this link should have an arrow. If the answer is "yes", replace this url with "/"

2021-04-21 09:47 UTC, y4izus commented on new-content/events/summer-school-2021.yaml
>      to: 'https://qiskit.org'
Ask @JRussellHuffman if this link should have an arrow. If the answer is "yes", replace this url with "/"

2021-04-21 09:47 UTC, y4izus commented on new-content/events/summer-school-2021.yaml
> +          action: 'events-summer-school > helpful-resources > install-here'
```suggestion
          action: 'events-summer-school > helpful-resources > qiskit-install'
```

2021-04-21 10:57 UTC, y4izus requested changes
Thanks for the previous changes. I have more suggestions.

Also, the "What are the application requirements for the Summer School?" section under FAQ is duplicate.

Ask me for another review (hopefully the last one)

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
> +      action: 'events-summer-school > faq > qiskit-python-and-jupyter-notebooks'
```suggestion
      action: 'events-summer-school > faq > textbook-python-and-jupyter-notebooks'
```

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
>    url: https://qiskit.org/textbook/ch-prerequisites/python-and-jupyter-notebooks.html
The link says "linear algebra" but it's pointing to the jupyter notebooks. Also, I think the linear algebra section was removed from the textbook. could you check this and change the url in consequence please?

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
> +      action: 'events-summer-school > faq > quantum-computing-educators'
```suggestion
      action: 'events-summer-school > faq > ibm-quantum-educators-program'
```

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
>  qceducators:
Just to follow with how you're naming variables:

```suggestion
qCEducators:
```

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
> +mailtoQcEducators:
```suggestion
mailtoQCEducators:
```

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
> +      action: 'events-summer-school > faq > mailto-quantum-educators'
```suggestion
      action: 'events-summer-school > faq > mailto-quantum-educators-program'
```

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
> +      action: 'events-summer-school > faq > twitter-qiskit'
```suggestion
      action: 'events-summer-school > faq > qiskit-twitter'
```

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
> +      action: 'events-summer-school > faq > twitter-ibmresearch'
```suggestion
      action: 'events-summer-school > faq > ibmresearch-twitter'
```

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
> +      action: 'events-summer-school > faq > github-qiskit'
```suggestion
      action: 'events-summer-school > faq > qiskit-github'
```

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
> +      action: 'events-summer-school > faq > medium-qiskit'
```suggestion
      action: 'events-summer-school > faq > qiskit-medium'
```

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
> +      action: 'events-summer-school > faq > qiskit-subscribe'
```suggestion
      action: 'events-summer-school > faq > qiskit-youtube-subscribe'
```

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
> +      action: 'events-summer-school > faq > join-qiskit-slack'
```suggestion
      action: 'events-summer-school > faq > qiskit-slack-join'
```

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021-page/faq.md
> +      action: 'events-summer-school > faq > qiskit-events'
```suggestion
      action: 'events-summer-school > faq > qiskit-org-events'
```

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021.yaml
> +      action: 'events-summer-school > header > qiskit-org-home'
If you change the link, you should also change the segment action
```suggestion
      action: 'events-summer-school > header > ibm-research-blog'
```

2021-04-21 10:57 UTC, y4izus commented on new-content/events/summer-school-2021.yaml
> +      action: 'events-summer-school > header > qiskit-org-home'
```suggestion
      action: 'events-summer-school > header > ibm-research-blog'
```

2021-04-21 11:28 UTC, y4izus approved these changes
Thanks!

2021-04-21 11:28 UTC, merged