Update summer-school-2021.yaml
Qiskit/qiskit.org pull request #1718
Opened 2021-04-20 20:24 UTC by justjosie

Re-ordering of the mosaic items for optimum fit - updating curriculum

2021-04-20 20:49 UTC, techtolentino approved these changes
Looks good @justjosie 

Thanks!

2021-04-21 08:56 UTC, y4izus requested changes
Just a comment on the code :)

Please, resolve the conflicts and we can merge

2021-04-21 08:56 UTC, y4izus commented on new-content/events/summer-school-2021.yaml
> +      image: '/images/events/summer-school/IBM_System_One_display.jpg'
Please, follow the same kebab-case style we are using for all the image names: `IBM_System_One_display` -> `ibm-system-one-display`

2021-04-21 11:30 UTC, y4izus approved these changes
Thanks!

2021-04-21 12:44 UTC, merged