Mega dropdown menu links update
Qiskit/qiskit.org pull request #1836
Opened 2021-05-26 15:37 UTC by korgan00

Fix #1812 

Links updated to point to the internal beta.

2021-05-27 08:52 UTC, eddybrando approved these changes
LGTM! Thanks 🙂

2021-05-27 09:08 UTC, y4izus commented on constants/megaMenuLinks.ts
> +  LEARNING_QML,
Why did you add the QML content on the first column?

2021-05-27 15:19 UTC, y4izus commented on constants/megaMenuLinks.ts
> +  LEARNING_QML,
I'm going to ask to the product team :)

2021-06-07 07:57 UTC, y4izus requested changes
Thank Goyo! Just one more comment :)

2021-06-07 07:57 UTC, y4izus commented on constants/megaMenuLinks.ts
> +      action: `${actionPrefix} > ${sectionPrerequisites} > whole-section`
You can create a variable for `whole-section` because you use it several times

2021-06-07 08:21 UTC, y4izus approved these changes

2021-06-07 08:21 UTC, merged