Update summer school links
Qiskit/qiskit.org pull request #2187
Opened 2021-09-23 13:50 UTC by techtolentino

Based off the conversation and agreement by the team, we're updating the Textbook beta paths.

This PR is to update links that point to the Textbook beta.

2021-09-23 14:48 UTC, y4izus requested changes

2021-09-23 14:48 UTC, y4izus commented on pages/textbook-beta/summer-school/quantum-computing-and-quantum-learning-2021.vue
> +      url: 'https://learn.qiskit.org/summer-school/2021/qgss2021/lec1-1'
Should we remove the `qgss2021` part?

2021-09-23 14:54 UTC, techtolentino commented on pages/textbook-beta/summer-school/quantum-computing-and-quantum-learning-2021.vue
> +      url: 'https://learn.qiskit.org/summer-school/2021/qgss2021/lec1-1'
I think so... good call...

2021-09-27 13:52 UTC, y4izus approved these changes
Thank you very much!! LGTM!

2021-09-27 13:56 UTC, merged