Publish single systems page
Qiskit/qiskit.org pull request #2831
Opened 2022-10-07 11:23 UTC by frankharkins

## Changes

Adds the single systems page to qiskit.org

:warning: This is not ready to merge, still waiting on:

- [ ] Description text
- [ ] Prerequisites
- [ ] Placeholder images for unfinished pages

## Screenshots

2022-10-26 13:30 UTC, techtolentino requested changes
Very nice work here @frankharkins 

I've made a few comments/suggestions -- please let me know if you have any questions!

2022-10-26 13:30 UTC, techtolentino commented on components/learn/ExternalRecommendedReadings.vue
> +        {{ link.description }}
I think this should go within the `<span>` tags unless you saw an error that I might've missed.

2022-10-26 13:45 UTC, techtolentino requested changes
@frankharkins

I also see these warnings in the terminal:

<img width="1020" alt="Screen Shot 2022-10-26 at 6 42 21 AM" src="https://user-images.githubusercontent.com/6276074/198042100-7a35dc32-c423-4b77-94ce-f90302fe544c.png">


To satisfy these errors, we'll need to add this to all the pages that extend CourseOverviewPage

`ExternalRecommendedReadingPreamble = ''`

For example, for this file: **quantum-simulation-summer-school-2022**

<img width="906" alt="Screen Shot 2022-10-26 at 6 44 02 AM" src="https://user-images.githubusercontent.com/6276074/198042796-d084cec4-4e2e-456c-a60e-28a1da2f1fe0.png">

2022-10-26 16:46 UTC, frankharkins commented on components/learn/ExternalRecommendedReadings.vue
>      <h2>
Awesome, this looks loads better, thanks

2022-10-27 15:49 UTC, techtolentino approved these changes
Awesome work here @frankharkins 

LGTM

🚢

2022-10-28 07:30 UTC, merged