feat: use "Script Setup" in pages
Qiskit/qiskit.org pull request #2937
Opened 2023-01-25 15:28 UTC by eddybrando

## Changes

Similar to https://github.com/Qiskit/qiskit.org/pull/2935, this PR changes the Vue components in the "pages" directory to make them use Script Setup.

This isn't intended to work as-is and will need further changes, but is required to continue the migration to Vue 3.

Closes #2936

2023-01-31 09:21 UTC, y4izus requested changes
Thank you!! Could you take a look at my comments?

2023-02-01 12:43 UTC, eddybrando commented on pages/advocates/index.vue
>  import QiskitPage from '~/components/logic/QiskitPage.vue'
Yes, this is mostly a reminder for reference about the "logic" pages, which will be refactored with https://github.com/Qiskit/qiskit.org/issues/2938.

2023-02-01 12:47 UTC, eddybrando commented on pages/blockbuster.vue
> +<script setup lang="ts">
Done in https://github.com/Qiskit/qiskit.org/pull/2937/commits/b51b39ea93c9bf3aa7773893607032fe6c672c84.

2023-02-01 12:48 UTC, eddybrando commented on pages/events/index.vue
> +const updateFilter = (filter: string, filterValue: string, isSelected: boolean): void => {
Done in https://github.com/Qiskit/qiskit.org/pull/2937/commits/940839e0f78d7a4513c1764eb574ddcf601f6237.

2023-02-01 12:48 UTC, eddybrando commented on pages/events/index.vue
> +const getCheckedFilters = (filter: string) => (this as any)[filter]
Done in https://github.com/Qiskit/qiskit.org/pull/2937/commits/940839e0f78d7a4513c1764eb574ddcf601f6237.

2023-02-01 16:51 UTC, y4izus approved these changes

2023-02-01 16:51 UTC, merged