Feat/3030 learn pages nuxt 3
Qiskit/qiskit.org pull request #3037
Opened 2023-03-20 15:44 UTC by eddybrando

## Changes

This PR makes the necessary changes to all "learn" pages to make them work with Nuxt 3.

Closes #3030 

## Implementation details

## How to read this PR

## Screenshots

2023-03-20 19:17 UTC, techtolentino requested changes
Really good migration work here @eddybrando 

Just a couple of comments, but nothing major... 

Thank you!

2023-03-20 19:17 UTC, techtolentino commented on components/learn/StartLearningSection.vue
> +          <div class="cds--col-xlg-4 cds--col-lg-4">
Correct me if I'm wrong, but this could be updated to just `cds--col-lg-4`

2023-03-21 16:16 UTC, eddybrando commented on components/learn/StartLearningSection.vue
> +                  :to="cta.url"
It was a bug indeed.

In  **/components/ui/BasicLink.vue* we had `:target="isExternal && '_blank'"`, which compiles to `<a ... target="false">`, causing the link opening in a new tab for an external URLs.

Why these are "external" URLs is another issue, but it's related to the `isExternal` logic, which we can/should change at a later point when we start leveraging the power of the new version of `NuxtLink`. But is a general issue that we already have in the application, so it's out of scope.

Changing the code to `:target="isExternal ? '_blank' : undefined"` makes it work as expected.

Fixed in https://github.com/Qiskit/qiskit.org/pull/3037/commits/02524b485c15b2cdaf1bb27126745104844c7ad7.

2023-03-21 16:18 UTC, techtolentino commented on components/learn/StartLearningSection.vue
> +                  :to="cta.url"
thanks for explaining this... this is good to know!

2023-03-22 10:11 UTC, merged