feat(providers): yaml content
Qiskit/qiskit.org pull request #3130
Opened 2023-04-14 14:56 UTC by eddybrando

## Changes

This PR makes it possible to fetch the providers data from YAML files instead of JSON using the [Nuxt Content module](https://content.nuxtjs.org/).

2023-04-17 07:56 UTC, y4izus requested changes
Thank you Eddy! Just some small modifications on naming and typing

2023-04-17 13:29 UTC, eddybrando commented on types/providersContent.ts
> +import type { ParsedContent } from "@nuxt/content/dist/runtime/types";
Changed in https://github.com/Qiskit/qiskit.org/pull/3130/commits/ea691ab3fb3e10e7aa0a6ffe2c8acd7f16e855fa

2023-04-17 15:16 UTC, eddybrando commented on components/Landing/LandingQuickStart/LandingQuickStartComponent.vue
> +const providersData = data.value!.body as ProviderObject[];
Changed in https://github.com/Qiskit/qiskit.org/pull/3130/commits/b7d00de25b2859c4b54b3b08ad095a2b4f029da7

2023-04-17 15:16 UTC, eddybrando commented on pages/providers.vue
> +const contentSections = providersData.value as ProvidersSectionParsedContent[];
Changed in https://github.com/Qiskit/qiskit.org/pull/3130/commits/b7d00de25b2859c4b54b3b08ad095a2b4f029da7

2023-04-17 15:28 UTC, eddybrando commented on pages/providers.vue
> +const contentSections = providersData.value as ProvidersSectionParsedContent[];
Sorry, changed again in https://github.com/Qiskit/qiskit.org/pull/3130/commits/b9fa6038323c239dc43a000faa1b689fe29248d9

2023-04-17 15:28 UTC, eddybrando commented on components/Landing/LandingQuickStart/LandingQuickStartComponent.vue
> +const providersData = data.value!.body as ProviderObject[];
Sorry, changed again in https://github.com/Qiskit/qiskit.org/pull/3130/commits/b9fa6038323c239dc43a000faa1b689fe29248d9

2023-04-18 08:44 UTC, y4izus approved these changes
Thank you Eddy!

2023-04-18 08:45 UTC, merged