feat(landing): Updates qiskit definition
Qiskit/qiskit.org pull request #3142
Opened 2023-04-19 10:38 UTC by y4izus

## Changes

Part of https://github.com/Qiskit/qiskit.org/issues/3125

Updates Qiskit definition

## Implementation details

We need to replace the current Qiskit definition with this one: _Qiskit {{ qiskitPronunciation }} is an open-source SDK for working with quantum computers focus in how build circuits and optimize them using the last transpiler passes, and bringing access to the last quantum hardware interfaces._

## How to read this PR

Go to the landing page and make sure that the description is correct

2023-04-19 10:45 UTC, eddybrando requested changes
I believe that we need to review the copy.

2023-04-19 10:52 UTC, y4izus commented
Waiting for the final text, I put the PR on ON-HOLD

2023-04-19 13:08 UTC, techtolentino commented
Quick note: once you have the final definition, we might want to update it in the site `meta description`, which I believe pulls from [package.json](https://github.com/Qiskit/qiskit.org/blob/yg-updates-qiskit-definition/package.json#L4)

2023-06-27 07:27 UTC, 1ucian0 commented
![xlg-1312px-16 column-3](https://github.com/Qiskit/qiskit.org/assets/766693/de099762-87dd-4dac-954d-792ac21a25ba)

2023-06-29 11:09 UTC, y4izus reviewed
Could you take a look at my comments? I didn't have time to finish all the code review, so @eddybrando please, could you review it too?

2023-06-29 11:09 UTC, y4izus commented on components/Landing/HeroMoment/LandingHeroMomentComponent.vue
> +            alt="Laptop"
Could you add more description to the `alt`? maybe we can reference to the code too

2023-06-29 12:15 UTC, eddybrando commented
This is design file: https://www.figma.com/file/CM5H3pOzE1CKnF0WoMYFZQ/3329-Utility-messaging?type=design&node-id=222-7829&mode=design&t=TGPYVp6UKABoZlXp-0

2023-06-29 12:21 UTC, eddybrando commented on components/Landing/HeroMoment/LandingHeroMomentComponent.vue
> +      width: 793px;
We usually don't work with such specific sizes but rather proportional, responsive sizes. Is there a need to do it like this in this specific case? This also goes for the other very specific size definitions in these styles.

2023-06-29 12:22 UTC, eddybrando commented on components/Landing/HeroMoment/LandingHeroMomentComponent.vue
> +    font-size: 5rem;
We should use a font definition from the reusable defined variables that we get from the Carbon library, like we do in the rest of the codebase.

2023-06-29 12:23 UTC, eddybrando commented on components/Landing/HeroMoment/LandingHeroMomentComponent.vue
> +      font-size: 7rem;
We should use a font definition from the reusable defined variables that we get from the Carbon library, like we do in the rest of the codebase.

2023-06-29 12:24 UTC, eddybrando commented on components/Landing/HeroMoment/LandingHeroMomentComponent.vue
> +      border-width: 1px 0 0;
We're defining border-width twice.

2023-06-29 18:09 UTC, techtolentino requested changes
Left a few comments... it's coming along nicely

Thanks @paaragon

2023-06-29 18:09 UTC, techtolentino commented on components/Landing/HeroMoment/LandingHeroMomentComponent.vue
> +            class="cds--col-md-4 cds--col-lg-5 cds--col-xlg-5 cds--col-max-7 hero-moment__title"
I don't normally see the carbon grid classes being applied to a text element. Normally, they're classes of a surrounding `div`. 

I'd suggest

```html
<div class="cds--col-md-4 cds--col-lg-5 cds--col-max-7">
  <h1 class="hero-moment__title"></h1>
</div>
```

2023-06-29 18:09 UTC, techtolentino commented on components/Landing/HeroMoment/LandingHeroMomentComponent.vue
> +            class="cds--col-sm cds--col-md-4 cds--col-lg-5 cds--col-xlg-5 hero-moment__description"
if we have `cds--col-lg-5`, do we also need `cds--col-xlg-5`?

2023-07-05 09:15 UTC, y4izus commented
Closing this is favor of https://github.com/Qiskit/qiskit.org/pull/3396

2023-07-05 09:15 UTC, closed without merging