refactor: components naming
Qiskit/qiskit.org pull request #3387
Opened 2023-06-29 11:45 UTC by eddybrando

## Changes

This PR changes the names of our components to align with the conventions that the team agreed upon in a meeting this week.

Closes #3136 

## Implementation details

## How to read this PR

## Screenshots

2023-06-29 15:54 UTC, paaragon requested changes
I think we should also rename the `public` subfolders. For example `/public/images/landing-page/` -> `/public/images/home/`

2023-06-29 16:30 UTC, techtolentino submitted a review, later dismissed
@eddybrando this is awesome work

I'm not sure if my feedback should be for _this_ PR, or a separate one.

I'm basically curious if there could be some 'refactoring effort' of simplifying our component names, based on how we organize components. 

In this first review, I use the Advocates card as an example.

2023-06-30 15:34 UTC, y4izus requested changes
Awesome refactor!! I've just have some small things :D

2023-06-30 15:34 UTC, y4izus commented on README.md
> +## 🏷️ Naming Conventions
Really helpful, thank you!

2023-06-30 15:34 UTC, y4izus commented on components/Advocates/MeetTheAdvocates/AdvocatesMeetTheAdvocatesCard.vue
> +    class="advocates-meet-the-advocates-card"
I agree, but I also think that refactoring that is out of the scope of this PR. We can create a new issue for talking about this or discussing it offline

2023-06-30 15:34 UTC, y4izus commented on components/Home/QuickStart/HomeQuickStart.vue
> +  <article class="cds--grid page-section home-quick-start">
Do we need `QuickStart` here? Maybe `HomeProviders` is enough

2023-06-30 15:34 UTC, y4izus commented on components/Ui/UiCta.vue
>        class="cta__icon"
Class naming should be change on this file too. Example:

```suggestion
      class="ui-cta__icon"
```

2023-06-30 15:34 UTC, y4izus commented on pages/ecosystem.vue
> +    <LayoutLeadSpaceFixed class="ecosystem-header__hero">
Should be... ?

```suggestion
    <LayoutLeadSpaceFixed class="ecosystem__header">
```

2023-06-30 15:34 UTC, y4izus commented on pages/events/summer-school-2022.vue
>    <main class="summer-school-page">
Should be...? 

```suggestion
  <main class="summer-school-2022-page">
```

2023-06-30 15:34 UTC, y4izus commented on pages/events/summer-school-2023.vue
>    <main class="summer-school-page">
Should be...? 

```suggestion
  <main class="summer-school-2023-page">

2023-06-30 15:34 UTC, y4izus commented on pages/events/index.vue
>    <div class="event-page">
```suggestion
  <div class="events-page">
```

2023-07-04 15:12 UTC, y4izus approved these changes

2023-07-04 15:14 UTC, paaragon approved these changes

2023-07-04 15:15 UTC, merged