fix(provider-code): newlines preserved in UI
Qiskit/qiskit.org pull request #3445
Opened 2023-07-20 23:01 UTC by jackoconnordev

## Changes

Newlines in the text provided to provider code blocks will now appear in the UI.

Also added (I believe) missing newlines in the source text for some provider code. All comments should have a newline above them right?

Fixes #3174 

## Implementation details

Newline characters aren't preserved by \<pre\> tag but spaces are. The laptop code block on the homepage's
text is hardcoded on the homepage and it includes space characters in the blank lines.

The provider text used newline characters on blank lines but for some reason \<pre\> tags don't preserve that.
Fix was to just use spaces instead.

The previous attempt to fix newlines not appearing ended up overpowered using `computed`
so I've streamlined it a bit since this isn't a dynamic component.

## Screenshots

### Newlines not rendering

#### Before

<img width="905" alt="image" src="https://github.com/Qiskit/qiskit.org/assets/134723582/57e8b01e-3683-4b24-85a4-90e083d974ef">

#### After

<img width="905" alt="image" src="https://github.com/Qiskit/qiskit.org/assets/134723582/febef345-853b-46cb-be8a-1df1f6d4321c">

2023-07-21 06:53 UTC, jackoconnordev commented
Can't find the option to convert back to draft sorry so I'll close and open a new one when found. The fix was only working on dev server for me, I checked previewing a build and the whitespace disappears again. It's possible that Nuxt build removes the empty lines from the source text? I will attempt to verify.

The npm run generate step of the build action still can't find the airtable key for me for some reason so there's no live preview of the issue. Not sure what I'd doing wrong with that, if anything.

2023-07-24 19:22 UTC, techtolentino requested changes
Hi @jackoconnordev thanks for the PR

Please see if this is causing any issues. When I checkout the PR locally, I'm not able to see new code snippets per provider in the homepage quick start switcher.

2023-07-24 19:22 UTC, techtolentino commented on components/Ui/UiCodeSnippet.vue
> +}
is this working on your side, @jackoconnordev?


Uploading Screen Recording 2023-07-24 at 12.21.04 PM.mov…

2023-07-24 20:02 UTC, jackoconnordev commented
I wrongly suggested there was no need for the UICodeSnippet text to be reactive. The text variable is now computed at each rerender again and should work as intended. Thanks for spotting my mistake @techtolentino.

(Please excuse the terrible quality 720p was just over the 10mb limit. The text changing on the homepage should still be clear in the second half of the video.)

https://github.com/Qiskit/qiskit.org/assets/134723582/aaa97634-6911-40c8-94ed-45c6be93e7cd

2023-07-25 17:03 UTC, techtolentino commented
@jackoconnordev - since you also approve of https://github.com/Qiskit/qiskit.org/pull/3450, we can close this.

Thank you for your involvement.

Let's wait on @y4izus to also review, then we can merge that PR...

2023-07-25 17:03 UTC, closed without merging