feat: remove references to Terra
Qiskit/qiskit.org pull request #3512
Opened 2023-08-21 17:34 UTC by techtolentino

## Changes

Close #3507 

## Implementation details

- update URL that linked to `/qiskit-terra`, now pointing to `/qiskit`
- changed property from `terraVersion` to `qiskitVersion`
- updated table header to say `Qiskit Version` (before it was `Qiskit Terra Version`

## Screenshots

https://github.com/Qiskit/qiskit.org/assets/6276074/580e39a1-4955-4826-a371-0a1abb72067d

2023-08-22 09:26 UTC, eddybrando requested changes
Thank you @techtolentino!

The `hooks/mock/content/ecosystem/members.json` appears to also have several mentions of "terra". I think that we should change those too.

2023-08-22 09:26 UTC, eddybrando commented on components/Ecosystem/EcosystemCardTestResults.vue
> +    :columns="['Status', 'Test Type', `Qiskit Version`, 'Test Logs']"
We can use `'` here:

```suggestion
    :columns="['Status', 'Test Type', 'Qiskit Version', 'Test Logs']"
```

2023-08-22 12:26 UTC, techtolentino commented
> Thank you @techtolentino!
> 
> The `hooks/mock/content/ecosystem/members.json` appears to also have several mentions of "terra". I think that we should change those too.

@eddybrando - done here https://github.com/Qiskit/qiskit.org/pull/3512/commits/08e48a5f3a091a9438a2f1577efde2cb379a64d8

2023-08-23 11:00 UTC, eddybrando approved these changes

2023-08-23 12:33 UTC, merged